id: P5BBEBB8E
initial_creation_type: ocr
source_metadata:
  volumes:
    6dd3dcaf2bbf40a5a9f69ad87b4436e5:
      base_file: v057.txt
      image_group_id: I1PD95902
      title: ''
      total_pages: 1605
      volume_number: 57
